server:
  port: 9999

spring:
  application:
    name: itoken-admin
  boot:
    admin:
      client:
        url: http://182.92.115.106:9999
        instance:
          prefer-ip: true
  zipkin:
    base-url: http://182.92.115.106:8280

eureka:
  client:
    service-url:
      defaultZone: http://182.92.115.106:8180/eureka/,http://182.92.115.106:8181/eureka/,http://182.92.115.106:8182/eureka/ # 注册中心地址
  instance:
    prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 暴露所有的监控信息
        include: health,info