server:
  port: 8180

spring:
  application:
    name: itoken-eureka
  boot:
    admin:
      client:
        url: http://122.51.109.246:9999
        instance:
          prefer-ip: true
  zipkin:
    base-url: http://122.51.109.246:8280

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8180/eureka/,http://${eureka.instance.hostname}:8181/eureka/,http://${eureka.instance.hostname}:8182/eureka/ # 注册中心地址
  instance:
    hostname: 122.51.109.246
    prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 暴露所有的监控信息
        include: health,info