server:
  port: 8480

spring:
  application:
    name: itoken-admin-service
  boot:
    admin:
      client:
        url: http://localhost:9999
        instance:
          prefer-ip: true
  zipkin:
    base-url: http://localhost:8280
  datasource:
    url: jdbc:mysql://47.107.226.177:3306/itoken_service_admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    # MySQL 8.x: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8180/eureka/ # 注册中心地址
  instance:
    prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 暴露所有的监控信息
        include: health,info

mybatis:
  type-aliases-package: com.lee.itoken.service.admin.domain
  mapper-locations: classpath:mapper/*.xml