server:
  port: 8180

spring:
  application:
    name: itoken-server

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 注册中心地址
  instance:
    hostname: localhost
