server:
  port: 8280

spring:
  application:
    name: itoken-zipkin
  zipkin:
    base-url: http://122.51.109.246:8280
  boot:
    admin:
      client:
        url: http://122.51.109.246:9999
        instance:
          prefer-ip: true
eureka:
  client:
    service-url:
      defaultZone: http://122.51.109.246:8180/eureka/,http://122.51.109.246:8181/eureka/,http://122.51.109.246:8182/eureka/ # 注册中心地址
  instance:
    prefer-ip-address: true

# 链路追踪相关依赖
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
  metrics:
    web:
      server:
        auto-time-requests: false
