server:
  port: 8200
spring:
  application:
    name: itoken-service-admin
  boot:
    admin:
      client:
        url: http://localhost:9999
        instance:
          prefer-ip: true
  zipkin:
    base-url: http://localhost:8280
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.99.37.67:3307/itoken-service-admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    # MySQL 8.x: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8180/eureka/ # 注册中心地址
  instance:
    prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 暴露所有的监控信息
        include: health,info

#mybatis
mybatis-plus:
  # Maven多模块项目的扫描路径需要以classpath*开头,即加载多个jar包下的XML文件
  mapper-locations: classpath:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lee.itoken.service.admin.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
#    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
#    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  db-config:
    table-prefix: tb_
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true