server:
  port: 8180

spring:
  application:
    name: itoken-eureka
  boot:
    admin:
      client:
        url: http://47.99.37.67:9999
        instance:
          prefer-ip: true
  zipkin:
    base-url: http://47.99.37.67:8280

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 注册中心地址
  instance:
    hostname: 47.99.37.67
    prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 暴露所有的监控信息
        include: health,info