server:
  port: 8480

spring:
  application:
    name: itoken-service-admin
  boot:
    admin:
      client:
        url: http://47.99.37.67:9999
        instance:
          prefer-ip: true
  zipkin:
    base-url: http://47.99.37.67:8280

eureka:
  client:
    service-url:
      defaultZone: http://47.99.37.67:8180/eureka/ # 注册中心地址
  instance:
    prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 暴露所有的监控信息
        include: health,info