server:
  port: 8180

spring:
  application:
    name: itoken-eureka
  boot:
    admin:
      client:
        url: http://localhost:9999
        instance:
          prefer-ip: true
  zipkin:
    base-url: http://localhost:8280

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 注册中心地址
  instance:
    hostname: localhost
    prefer-ip-address: true